import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ToastListener } from "@/components/toast-listener";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster position="bottom-right" />
        <ToastListener />
        {children}
      </body>
    </html>
  );
}
